### ISSUE TITLE
Error trace when calling pushover plugin 

### ISSUE THREAD

**Issue by normen** [thijsbekke/OctoPrint-Pushover#21]
Hi,

I found this trace in my logs but from what I can tell the pushover plugin seems to work as intended. Can't imagine such a trace is intended though so I thought I'd report it :)

Using Octoprint 1.3.7rc2 and Pushover Plugin 0.2.1

`2018-03-29 01:22:57,754 - octoprint.plugin - ERROR - Error while calling plugin pushover
Traceback (most recent call last):
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint/plugin/__init__.py", line 225, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_pushover/__init__.py", line 229, in on_event
    payload["message"] = getattr(self, event)(payload)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_pushover/__init__.py", line 177, in PrintFailed
    file = os.path.basename(payload["name"])
KeyError: 'name'
`

**Comment by thijsbekke** [comment]
Thanks for reporting this issue, a bit late response, sorry for that. It is fixed in my latest commit and will be in the next release.
